# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
        with:
    # The branch, tag or SHA to checkout. When checking out the repository that
    # triggered a workflow, this defaults to the reference or SHA for that event.
    # Otherwise, defaults to `master`.
            ref: 'Testing'
      - name: Cypress run Chrome
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm run test:e2e:ci:chrome
      - name: Cypress run Firefox
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm run test:e2e:ci:firefox
      - name: Cypress run Edge
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm run test:e2e:ci:edge
